{
 "title": "Statup",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "label_values(statup_service_latency, name)"
   }
  ]
 },
 "panels": [
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "statup_service_online{name=\"${service}\"}"
    }
   ]
  },
  {
   "title": "${service} Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "statup_service_latency{name=\"${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 2 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "statup_service_latency{name=\"${service}\"}"
    }
   ]
  },
  {
   "title": "${service} Response Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "statup_service_response_length{name=\"${service}\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Response Status Code",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "statup_service_status_code{name=\"${service}\"}"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 12 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "statup_service_response_length{name=\"${service}\"}"
    }
   ]
  }
 ]
}