FROM cypress/browsers:chrome67
MAINTAINER "Hunter Long (https://github.com/hunterlong)"
# Statup 'test' image for running a full test using the production environment

WORKDIR $HOME/statup
ADD dev/test .

ENV VERSION=v0.46

RUN wget -q https://github.com/hunterlong/statup/releases/download/$VERSION/statup-linux-alpine.tar.gz && \
    tar -xvzf statup-linux-alpine.tar.gz && \
    chmod +x statup && \
    mv statup /usr/local/bin/statup

RUN npm install node-sass
ENV SASS=node-sass
RUN npm install
RUN npm run test-docker