FROM golang:1.10.3-alpine

RUN apk update && apk add git g++ libstdc++ ca-certificates

WORKDIR $GOPATH/src/github.com/hunterlong/statup/

COPY . $GOPATH/src/github.com/hunterlong/statup/
RUN go get github.com/GeertJohan/go.rice/rice
RUN go get -d -v
RUN rice embed-go
RUN go install

RUN wget -q https://assets.statup.io/sass && \
      chmod +x sass && \
      mv sass /usr/local/bin/sass

ENV IS_DOCKER=true
ENV SASS=/usr/local/bin/sass
ENV CMD_FILE=/usr/bin/cmd

RUN printf "#!/usr/bin/env sh\n\$1\n" > $CMD_FILE && \
      chmod +x $CMD_FILE

WORKDIR /app
VOLUME /app
EXPOSE 8080
CMD ["/go/bin/statup"]